/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package diceRoll;

import diceRoll.Controller.DiceController;
import diceRoll.View.DiceGUI;

import javax.swing.*;

public class App 
{
    public static void main(String[] args) 
    {
        DiceGUI gui = new DiceGUI();
        DiceController diceController = new DiceController(gui);

        JFrame mainFrame = new JFrame("Dice Roll");
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JPanel mainPanel = new JPanel();
        mainPanel.add(gui);

        mainFrame.add(mainPanel);
        mainFrame.pack();
        mainFrame.setVisible(true);
    }
}
